name: pfitmap-nextflow-env
channels:
  - anaconda
  - conda-forge
  - defaults
  - bioconda
  - biocore
  - matricaria
dependencies:
  - hmmer=3.3.0 # Don't change, hmmer 3.3.2 fails!
  - pfitmap-db=1.10
  - r-stringi
  - r-r.utils
